#!/bin/bash +x

usage() {
   echo "./SW_STAP_01 <number of socket>"
}

NumSocket=$1
echo $SystemConfig $NumSocket

GetDeviceInformation(){
   CMDRST="$(/usr/sbin/lspci | grep bcc0)"
   DEVINFO1="${CMDRST[0]}"
   DEVINFO2="${CMDRST[1]}"

   echo  $DEVINFO1
   Bus1="${DEVINFO1:0:2}"
   Dev1="${DEVINFO1:3:2}"
   Func1="${DEVINFO1:6:1}"
   Bus2="${DEVINFO1:67:2}"
   Dev2="${DEVINFO1:3:2}"
   Func2="${DEVINFO1:6:1}"
}

GetDeviceInformation
bus1="0x"$Bus1
bus2="0x"$Bus2

if [[ $NumSocket -eq 1 ]]; then
   ./Signal_Tap 

   if [[ $? -eq 0 ]]; then 
      echo "Test PASS on 1 socket system !!!"
      exit 0
   else 
      echo "Test FAILED on 1 socket system !!!"
      exit 1
   fi
fi

if [[ $NumSocket -eq 2 ]]; then
   echo ./Signal_Tap --bus=$bus1
   ./Signal_Tap --bus=$bus1 

   result1=$?
   
   echo ./Signal_Tap --bus=$bus2
   ./Signal_Tap --bus=$bus2
      
   result2=$?  
  
   if [[ $result1 -eq 0 && $result2 -eq 0 ]] ; then 
      echo "Test PASS on 2 sockets system !!!"
      exit 0
   else 
      echo "Test FAILED on 2 sockets system !!!"
      exit 1
   fi
fi


