#!/bin/bash

## ************************************************
##  Set AAL lib path
## ************************************************
cd ../../../../aalsdk/myinst/usr/local/lib/
export LD_LIBRARY_PATH=$PWD
cd ../../../../valapps/Partial_Reconfig/PR_TwoApp/


## ************************************************
##  run PR app with bitstream
## ************************************************

echo $1

echo  "\\n./Hello_ALI_NLB/SW/helloALInlb   \\n"
nlb_app/ALInlb $1

echo  "\\n **** DONE**** \\n"

sleep 10


