#!/bin/bash +x

usage() {
   echo "./SW_BUF_01_04 <number of socket> "
}

echo $SystemConfig

GetDeviceInformation(){
   CMDRST="$(lspci | grep bcc0)"
   DEVINFO1="${CMDRST[0]}"
   DEVINFO2="${CMDRST[1]}"

   echo  $DEVINFO1
   Bus1="${DEVINFO1:0:2}"
   Dev1="${DEVINFO1:3:2}"
   Func1="${DEVINFO1:6:1}"
   Bus2="${DEVINFO1:67:2}"
   Dev2="${DEVINFO1:3:2}"
   Func2="${DEVINFO1:6:1}"
}

GetFpgaDiagToWorkDirectory(){

   ToolPATH=$ToolPATH
   Tool=$ToolPATH"/fpgadiag"
   echo $Tool

   #copy fpgadiag tool to local directory
   if [ -f fpgadiag ]; then 
      echo "remove fpgadiag "
      rm fpgadiag
   fi
   echo "copy fpgadiag "
   cp $Tool .
}

GetHelloALINLBApp(){
   App=$SampleAppPATH"Hello_ALI_NLB/SW/helloALInlb"
   
   echo $App

   #copy fpgadiag tool to local directory
   if [ -f helloALInlb ]; then 
      echo "remove helloALInlb "
      rm helloALInlb
   fi
   echo "copy helloALInlb "
   cp $App .

}

TwoSocketsTest(){
   echo "Run FPGADIAG on 2 sockets system"
   
   if [ "$SystemConfig" == "native" ]; then
      if [ ! -f fpgadiag ]; then 
         echo "fpgadiag doesn't exist"
         exit 1
      else
         ./fpgadiag --mode=lpbk1 --target=fpga --begin=65535 --read-vc=vh0 --write-vc=vh0 \
               --bus-number="0x"$Bus1

         result1=$?
     
         ./fpgadiag --mode=lpbk1 --target=fpga --begin=65535 --read-vc=vh0 --write-vc=vh0 \
               --bus-number="0x"$Bus2
      
         result2=$?  
     
         if [[ $result1 -eq 0 && $result2 -eq 0 ]] ; then 
            echo "Test PASS on 2 sockets system !!!"
            exit 0
         else 
            echo "Test FAILED on 2 sockets system !!!"
            exit 1
         fi
      fi
   fi

   if [ "$SystemConfig" == "vm" ]; then
      if [ ! -f helloALInlb ]; then 
         echo "helloALInlb doesn't exist"
         exit 1
      else
         ./helloALInlb --bus-number="0x"$Bus1

         result3=$?
     
         ./helloALInlb --bus-number="0x"$Bus2
      
         result4=$?  
     
         if [[ $result3 -eq 0 && $result4 -eq 0 ]] ; then 
            echo "Test PASS on 2 sockets system !!!"
            exit 0
         else 
            echo "Test FAILED on 2 sockets system !!!"
            exit 1
         fi
      fi
   fi   
}

OneSocketTest(){

   if [ "$SystemConfig" == "native" ]; then
      ./fpgadiag --mode=lpbk1 --target=fpga --begin=65535 --read-vc=vh0 --write-vc=vh0 

      if [[ $? -eq 0 ]]; then 
         echo "Test PASS on 1 socket system !!!"
         exit 0
      else 
         echo "Test FAILED on 1 socket system !!!"
         exit 1
      fi
   fi

   if [ "$SystemConfig" == "vm" ]; then
      ./helloALInlb 

      if [[ $? -eq 0 ]]; then 
         echo "Test PASS on 1 socket system !!!"
         exit 0
      else 
         echo "Test FAILED on 1 socket system !!!"
         exit 1
      fi
   fi
}

GetDeviceInformation
echo "$Bus1:$Dev1:$Func1"
echo "$Bus2:$Dev2:$Func2"

GetFpgaDiagToWorkDirectory
GetHelloALINLBApp

# run fpgadiag/HelloALINLBApp test
if [[ $1 -eq 2 ]]; then
   
   TwoSocketsTest 
 
else

   OneSocketTest
fi

#clean up fpgadiag
rm fpgadiag



 

   

