#############################################################################
#                                                                           #
# Intel AFU Simulation Environment 5.0.0                                    #
# This file was generated by AALSDK/ase/scripts/generate_ase_environment.py #
#                                                                           #
#############################################################################

DUT_VLOG_SRC_LIST = vlog_files.list 

DUT_INCDIR = /home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/cci_mpf+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/cci_mpf/cci-mpf-shims+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/cci_mpf/cci-if+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/cci_mpf/cci-mpf-if+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/cci_mpf/cci-mpf-prims+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/nlb_mpf_400+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/nlb_mpf_400/include_files+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/nlb_mpf_400/include_files/common+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/nlb_mpf_400/par+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/build+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/build/nlb_mpf_400_hw.exe.daidir+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/build/nlb_mpf_400_hw.exe.daidir/debug_dump+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/build/csrc+/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/build/csrc/hsim+

ASEHW_FILE_LIST = \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/ccip_if_pkg.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/ase_pkg.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/outoforder_wrf_channel.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/counter.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/ase_fifo.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/latency_pipe.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/ccip_emulator.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/ccip_logger.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/ccip_sniffer.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/ase_top.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/sdp_ram.sv \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/stream_checker.sv \

# /home/rrsharma/xeon-fpga-src/shadow_aalsdk/aalsamples/Hello_ALI_VTP_NLB/HW/cci_mpf/cci-if/ccip_if_pkg.sv \

ASE_INCDIR = /home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/+

ASESW_FILE_LIST = \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/ase_ops.c \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/ipc_mgmt_ops.c \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/mem_model.c \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/protocol_backend.c \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/tstamp_ops.c \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/mqueue_ops.c \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/error_report.c \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/linked_list_ops.c \
	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/sw/randomness_control.c \


ASE_TOP = ase_top

SIMULATOR = VCS

#	/home/rrsharma/xeon-fpga-src/shadow_aalsdk/aaluser/ase/hw/ccip_if_pkg.sv \
