
#line 3 "aalclp.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 35
#define YY_END_OF_BUFFER 36
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[68] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       36,    4,    1,    3,    2,    8,    5,    7,    6,   24,
       21,   23,   22,   34,   32,   33,   11,    9,   10,   14,
       13,   12,   17,   15,   16,   20,   19,   18,   28,   25,
       27,   26,   31,   30,   29,    1,   33,    9,   10,   13,
       15,   16,   19,   25,   27,   30,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    5,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        6,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,

        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[7] =
    {   0,
        1,    2,    2,    3,    3,    4
    } ;

static yyconst flex_int16_t yy_base[79] =
    {   0,
        0,    0,    6,    0,   12,    0,   18,    0,   24,    0,
       30,    0,   36,    0,   42,    0,   48,    0,   54,    0,
       78,   79,    0,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   79,   79,   79,    0,   79,    0,    0,   79,
        0,   79,   79,    0,    0,   79,    0,   79,   79,    0,
        0,   79,   79,    0,   79,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   79,   75,   58,   74,
       60,   62,   73,   64,   66,   72,   70,   68
    } ;

static yyconst flex_int16_t yy_def[79] =
    {   0,
       67,    1,   67,    3,   67,    5,   67,    7,   67,    9,
       67,   11,   67,   13,   67,   15,   67,   17,   67,   19,
       67,   67,   68,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   69,   67,   70,   71,   67,
       72,   67,   67,   73,   74,   67,   75,   67,   67,   76,
       77,   67,   67,   78,   67,   68,   69,   70,   71,   72,
       73,   74,   75,   76,   77,   78,    0,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67
    } ;

static yyconst flex_int16_t yy_nxt[86] =
    {   0,
       22,   23,   23,   24,   25,   24,   26,   27,   27,   28,
       29,   28,   30,   31,   31,   32,   33,   32,   34,   35,
       35,   36,   36,   36,   37,   38,   38,   39,   39,   39,
       40,   40,   40,   41,   42,   41,   43,   44,   44,   45,
       45,   45,   46,   46,   46,   47,   48,   47,   49,   50,
       50,   51,   51,   52,   53,   53,   53,   54,   55,   54,
       57,   57,   59,   59,   60,   60,   62,   62,   63,   63,
       66,   66,   65,   64,   61,   58,   56,   67,   21,   67,
       67,   67,   67,   67,   67
    } ;

static yyconst flex_int16_t yy_chk[86] =
    {   0,
        1,    1,    1,    1,    1,    1,    3,    3,    3,    3,
        3,    3,    5,    5,    5,    5,    5,    5,    7,    7,
        7,    7,    7,    7,    9,    9,    9,    9,    9,    9,
       11,   11,   11,   11,   11,   11,   13,   13,   13,   13,
       13,   13,   15,   15,   15,   15,   15,   15,   17,   17,
       17,   17,   17,   17,   19,   19,   19,   19,   19,   19,
       69,   69,   71,   71,   72,   72,   74,   74,   75,   75,
       78,   78,   77,   76,   73,   70,   68,   21,   67,   67,
       67,   67,   67,   67,   67
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "../../clp/aalclp.l"
#line 2 "../../clp/aalclp.l"
// Copyright(c) 2013-2016, Intel Corporation
//
// Redistribution  and  use  in source  and  binary  forms,  with  or  without
// modification, are permitted provided that the following conditions are met:
//
// * Redistributions of  source code  must retain the  above copyright notice,
//   this list of conditions and the following disclaimer.
// * Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
// * Neither the name  of Intel Corporation  nor the names of its contributors
//   may be used to  endorse or promote  products derived  from this  software
//   without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING,  BUT NOT LIMITED TO,  THE
// IMPLIED WARRANTIES OF  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED.  IN NO EVENT  SHALL THE COPYRIGHT OWNER  OR CONTRIBUTORS BE
// LIABLE  FOR  ANY  DIRECT,  INDIRECT,  INCIDENTAL,  SPECIAL,  EXEMPLARY,  OR
// CONSEQUENTIAL  DAMAGES  (INCLUDING,  BUT  NOT LIMITED  TO,  PROCUREMENT  OF
// SUBSTITUTE GOODS OR SERVICES;  LOSS OF USE,  DATA, OR PROFITS;  OR BUSINESS
// INTERRUPTION)  HOWEVER CAUSED  AND ON ANY THEORY  OF LIABILITY,  WHETHER IN
// CONTRACT,  STRICT LIABILITY,  OR TORT  (INCLUDING NEGLIGENCE  OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,  EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#include <stdio.h>

#ifdef HAVE_SYS_TYPES_H
# include <sys/types.h>
#endif // HAVE_SYS_TYPES_H

#if HAVE_STDLIB_H
# include <stdlib.h>
#else
# error Required system header stdlib.h not found.
#endif // HAVE_STDLIB_H
#if HAVE_ERRNO_H
# include <errno.h>
#else
# error Required system header errno.h not found.
#endif // HAVE_ERRNO_H
#if HAVE_CTYPE_H
# include <ctype.h>
#else
# error Required system header ctype.h not found.
#endif // HAVE_CTYPE_H

#ifndef HAVE_STRCHR
#error Required system library fn strchr() not found.
#endif // HAVE_STRCHR

#include "aalsdk/aalclp/aalclp.h"

#ifdef WIN32
#include <windows.h>
   BOOL APIENTRY DllMain(HANDLE hModule,
                         DWORD  ul_reason_for_call,
                         LPVOID lpReserved)
   {
      HANDLE hTemp  = hModule;
      LPVOID lpVoid = lpReserved;
      switch ( ul_reason_for_call ) {
         case DLL_PROCESS_ATTACH :
         case DLL_THREAD_ATTACH  :
         case DLL_THREAD_DETACH  :
         case DLL_PROCESS_DETACH :
            break;
      }
      return TRUE;
   }
#endif // WIN32

/* All fn's return non-zero on error, unless otherwise noted. */

static int aalclp_on_nix_long_option_only(yyscan_t yyscanner, const char *option);
static int aalclp_on_nix_long_option(yyscan_t yyscanner, const char *option, const char *value);
static int aalclp_on_nix_short_option_only(yyscan_t yyscanner, const char *option);
static int aalclp_on_nix_short_option(yyscan_t yyscanner, const char *option, const char *value);
static int aalclp_on_dash_only(yyscan_t yyscanner);
static int aalclp_on_dash_dash_only(yyscan_t yyscanner);
static int aalclp_on_win_long_option_only(yyscan_t yyscanner, const char *option);
static int aalclp_on_win_long_option(yyscan_t yyscanner, const char *option, const char *value);
static int aalclp_on_win_short_option_only(yyscan_t yyscanner, const char *option);
static int aalclp_on_win_short_option(yyscan_t yyscanner, const char *option, const char *value);
static int aalclp_on_non_option(yyscan_t yyscanner, const char *nonoption);
static int aalclp_on_invalid(yyscan_t yyscanner, const char *invalid, size_t len);

/* flex-to-aalclp API */
/* ************************************************************************** */
/* flex scanner internals */

#define MAX_OPTION   256
static char option[MAX_OPTION] = { 0, };
static int  option_len         = 0;

#define begin_option(ch) \
do                       \
{                        \
   option[0]  = ch;      \
   option[1]  = 0;       \
   option_len = 1;       \
}while(0)

#define cont_option(str, len)                         \
do                                                    \
{                                                     \
   strncat(option, str, sizeof(option) - option_len); \
   option_len += len;                                 \
}while(0)

#define end_option() \
do                   \
{                    \
   option[0]  = 0;   \
   option_len = 0;   \
}while(0)

#define MAX_ARGUMENT 512
static char argument[MAX_ARGUMENT] = { 0, };
static int  argument_len           = 0;

#define cont_argument(str, len)                             \
do                                                          \
{                                                           \
   strncat(argument, str, sizeof(argument) - argument_len); \
   argument_len += len;                                     \
}while(0)

#define end_argument() \
do                     \
{                      \
   argument[0]  = 0;   \
   argument_len = 0;   \
}while(0)

#define my_begin(x) BEGIN(x)










#line 604 "aalclp.c"

#define INITIAL 0
#define DASH 1
#define DASHDASH 2
#define NONOPTION 3
#define NIXSHORTOPT 4
#define NIXSHORTOPTWS 5
#define NIXSHORTOPTSEQ 6
#define NIXSHORTOPTSEQWS 7
#define NIXLONGOPT 8
#define NIXLONGOPTWS 9

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (yyscan_t yyscanner);

#define YY_DECL int yylex (yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 144 "../../clp/aalclp.l"



#line 843 "aalclp.c"

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 68 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 79 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 147 "../../clp/aalclp.l"
/* eat whitespace */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 149 "../../clp/aalclp.l"
{
                                                            begin_option('-');
                                                            my_begin(DASH);
                                                         }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 154 "../../clp/aalclp.l"
{
                                                            yyless(0);
                                                            my_begin(NONOPTION);
                                                         }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 159 "../../clp/aalclp.l"
yyterminate(); /* success */
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 161 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 168 "../../clp/aalclp.l"
{ // -
                                                            yyless(0);
                                                            if ( aalclp_on_dash_only(yyscanner) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 178 "../../clp/aalclp.l"
{ // --
                                                            cont_option(yytext, yyleng);
                                                            my_begin(DASHDASH);
                                                         }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 183 "../../clp/aalclp.l"
{ // -a
                                                            cont_option(yytext, yyleng);
                                                            my_begin(NIXSHORTOPT);
                                                         }
	YY_BREAK
case YY_STATE_EOF(DASH):
#line 188 "../../clp/aalclp.l"
{ // -<EOF>
                                                            if ( aalclp_on_dash_only(yyscanner) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 197 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 204 "../../clp/aalclp.l"
{ // -a
                                                            my_begin(NIXSHORTOPTWS);
                                                         }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 208 "../../clp/aalclp.l"
{ // -ab
                                                            cont_option(yytext, yyleng);
                                                            my_begin(NIXSHORTOPTSEQ);
                                                         }
	YY_BREAK
case YY_STATE_EOF(NIXSHORTOPT):
#line 213 "../../clp/aalclp.l"
{ // -a
                                                            if ( aalclp_on_nix_short_option_only(yyscanner, option) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 222 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 229 "../../clp/aalclp.l"
{ // -a -
                                                            if ( aalclp_on_nix_short_option_only(yyscanner, option) ) {
                                                               yyterminate();
                                                            }

                                                            begin_option('-');
                                                            my_begin(DASH);
                                                         }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 238 "../../clp/aalclp.l"
{ // -a abc
                                                            strncpy(argument, yytext, sizeof(argument));
                                                            if ( aalclp_on_nix_short_option(yyscanner, option, argument) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            end_argument();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case YY_STATE_EOF(NIXSHORTOPTWS):
#line 249 "../../clp/aalclp.l"
{ // -a <EOF>
                                                            if ( aalclp_on_nix_short_option_only(yyscanner, option) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 258 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 15:
/* rule 15 can match eol */
YY_RULE_SETUP
#line 265 "../../clp/aalclp.l"
{ // -abc
                                                            my_begin(NIXSHORTOPTSEQWS);
                                                         }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 269 "../../clp/aalclp.l"
{ // -abcd
                                                            cont_option(yytext, yyleng);
                                                         }
	YY_BREAK
case YY_STATE_EOF(NIXSHORTOPTSEQ):
#line 273 "../../clp/aalclp.l"
{ // -abc<EOF>
                                                            char *p = option + 1;
                                                            char buf[3];

                                                            while ( *p ) {
                                                               buf[0] = '-';
                                                               buf[1] = *p;
                                                               buf[2] = 0;

                                                               if ( aalclp_on_nix_short_option_only(yyscanner, buf) ) {
                                                                  yyterminate();
                                                               }

                                                               ++p;
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 293 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 300 "../../clp/aalclp.l"
{ // -abc -
                                                            char *p = option + 1;
                                                            char buf[3];

                                                            while ( *p ) {
                                                               buf[0] = '-';
                                                               buf[1] = *p;
                                                               buf[2] = 0;

                                                               if ( aalclp_on_nix_short_option_only(yyscanner, buf) ) {
                                                                  yyterminate();
                                                               }

                                                               ++p;
                                                            }

                                                            begin_option('-');
                                                            my_begin(DASH);
                                                         }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 320 "../../clp/aalclp.l"
{ // -abc xyz
                                                            char *p = option + 1;
                                                            char buf[3];

                                                            while ( *p ) {
                                                               buf[0] = '-';
                                                               buf[1] = *p;
                                                               buf[2] = 0;

                                                               strncpy(argument, yytext, sizeof(argument));

                                                               if ( aalclp_on_nix_short_option(yyscanner, buf, argument) ) {
                                                                  yyterminate();
                                                               }

                                                               ++p;
                                                            }

                                                            end_option();
                                                            end_argument();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case YY_STATE_EOF(NIXSHORTOPTSEQWS):
#line 343 "../../clp/aalclp.l"
{ // -abc <EOF>
                                                            char *p = option + 1;
                                                            char buf[3];

                                                            while ( *p ) {
                                                               buf[0] = '-';
                                                               buf[1] = *p;
                                                               buf[2] = 0;

                                                               if ( aalclp_on_nix_short_option_only(yyscanner, buf) ) {
                                                                  yyterminate();
                                                               }

                                                               ++p;
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 363 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 369 "../../clp/aalclp.l"
{ // --
                                                            yyless(0);

                                                            if ( aalclp_on_dash_dash_only(yyscanner) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 380 "../../clp/aalclp.l"
{ // ---
                                                            cont_option(yytext, yyleng);
                                                            my_begin(NONOPTION);
                                                         }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 385 "../../clp/aalclp.l"
{  // --abc
                                                            cont_option(yytext, yyleng);
                                                            my_begin(NIXLONGOPT);
                                                         }
	YY_BREAK
case YY_STATE_EOF(DASHDASH):
#line 390 "../../clp/aalclp.l"
{ // --<EOF>
                                                            if ( aalclp_on_dash_dash_only(yyscanner) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 399 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 406 "../../clp/aalclp.l"
{ // --abc
                                                            my_begin(NIXLONGOPTWS);
                                                         }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 410 "../../clp/aalclp.l"
{ // --abcd=
                                                            my_begin(NIXLONGOPTWS);
                                                         }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 414 "../../clp/aalclp.l"
{ // --abcd
                                                            cont_option(yytext, yyleng);
                                                         }
	YY_BREAK
case YY_STATE_EOF(NIXLONGOPT):
#line 418 "../../clp/aalclp.l"
{ // --abc<EOF>
                                                            if ( aalclp_on_nix_long_option_only(yyscanner, option) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 427 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 434 "../../clp/aalclp.l"
{ // --abc -
                                                            if ( aalclp_on_nix_long_option_only(yyscanner, option) ) {
                                                               yyterminate();
                                                            }

                                                            begin_option('-');
                                                            my_begin(DASH);
                                                         }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 443 "../../clp/aalclp.l"
{ // --abc xyz
                                                            strncpy(argument, yytext, sizeof(argument));
                                                            if ( aalclp_on_nix_long_option(yyscanner, option, argument) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            end_argument();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case YY_STATE_EOF(NIXLONGOPTWS):
#line 454 "../../clp/aalclp.l"
{ // --abc <EOF>
                                                            if ( aalclp_on_nix_long_option_only(yyscanner, option) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 463 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 470 "../../clp/aalclp.l"
{
                                                            yyless(0);
                                                            if ( aalclp_on_non_option(yyscanner, option) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 480 "../../clp/aalclp.l"
{
                                                            cont_option(yytext, yyleng);
                                                         }
	YY_BREAK
case YY_STATE_EOF(NONOPTION):
#line 484 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_non_option(yyscanner, option) ) {
                                                               yyterminate();
                                                            }

                                                            end_option();
                                                            my_begin(INITIAL);
                                                         }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 493 "../../clp/aalclp.l"
{
                                                            if ( aalclp_on_invalid(yyscanner, yytext, yyleng) ) {
                                                               yyterminate();
                                                            }
                                                         }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 499 "../../clp/aalclp.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1404 "aalclp.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;
                          
			if ( b == NULL)
			{
			    num_to_read = 0;
			    YY_FATAL_ERROR(
				"fatal error - YY_CURRENT_BUFFER is NULL" );
			    break;
			}
                        
			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 68 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 68 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 67);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

//tsw        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
        b->yy_is_interactive = file ? (isatty( _fileno(file) ) > 0) : 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 499 "../../clp/aalclp.l"



#define aalclp_offset_of(__cont_type, __linksname) \
(unsigned long)( &( ((__cont_type *)((void *)0))->__linksname ) )

#define aalclp_container_of(__cont_type, __linksptr, __linksname) \
(__cont_type *) ( (unsigned char *)(__linksptr) - aalclp_offset_of(__cont_type, __linksname) )

#define aalclp_list_init(__l) (__l)->prev = (__l)->next = (__l)

#define aalclp_list_enqueue(__l, __x) \
do                                    \
{                                     \
   (__x)->prev       = (__l)->prev;   \
   (__x)->next       = (__l);         \
   (__l)->prev->next = (__x);         \
   (__l)->prev       = (__x);         \
}while(0)

#define aalclp_list_for_each_entry(__etype, __eptr, __l, __i)                      \
for ( (__i) = (__l)->next, (__eptr) = aalclp_container_of(__etype, __i, links) ;   \
         (__i) != (__l) ;                                                          \
            (__i) = (__i)->next, (__eptr) = aalclp_container_of(__etype, __i, links) )

static int
aalclp_init_callbacks(aalclp_callbacks *cb) {
   aalclp_list_init(&cb->listhead_nix_long_option_only.links);
   aalclp_list_init(&cb->listhead_nix_long_option.links);
   aalclp_list_init(&cb->listhead_nix_short_option_only.links);
   aalclp_list_init(&cb->listhead_nix_short_option.links);
   aalclp_list_init(&cb->listhead_dash_only.links);
   aalclp_list_init(&cb->listhead_dash_dash_only.links);
   aalclp_list_init(&cb->listhead_win_long_option_only.links);
   aalclp_list_init(&cb->listhead_win_long_option.links);
   aalclp_list_init(&cb->listhead_win_short_option_only.links);
   aalclp_list_init(&cb->listhead_win_short_option.links);
   aalclp_list_init(&cb->listhead_non_option.links);
   aalclp_list_init(&cb->listhead_invalid.links);
   return 0;
}

#define AALCLP_ADD(__what, __type)                                                        \
int aalclp_add_##__what(aalclp *scanner, __type *node) {                                  \
   if ( (NULL != node) && (NULL != node->cb) ) {                                          \
      aalclp_list_enqueue(&(scanner->callbacks.listhead_##__what.links), &(node)->links); \
      return 0;                                                                           \
   }                                                                                      \
   errno = EFAULT;                                                                        \
   return 1;                                                                              \
}


AALCLP_ADD(nix_long_option_only,  aalclp_option_only)
AALCLP_ADD(nix_long_option,       aalclp_option)
AALCLP_ADD(nix_short_option_only, aalclp_option_only)
AALCLP_ADD(nix_short_option,      aalclp_option)
AALCLP_ADD(dash_only,             aalclp_dash_only)
AALCLP_ADD(dash_dash_only,        aalclp_dash_only)
AALCLP_ADD(win_long_option_only,  aalclp_option_only)
AALCLP_ADD(win_long_option,       aalclp_option)
AALCLP_ADD(win_short_option_only, aalclp_option_only)
AALCLP_ADD(win_short_option,      aalclp_option)
AALCLP_ADD(non_option,            aalclp_non_option)
AALCLP_ADD(invalid,               aalclp_invalid)

AALCLP_API int
aalclp_init(aalclp *scanner) {
   if ( NULL == scanner ) {
      errno = EFAULT;
      return 1;
   }

   scanner->scanner = NULL;
   aalclp_init_callbacks(&scanner->callbacks);

   return yylex_init_extra((YY_EXTRA_TYPE)scanner,&scanner->scanner);
}

AALCLP_API int
aalclp_destroy(aalclp *scanner) {
   int res;

   if ( NULL == scanner ) {
      errno = EFAULT;
      return 1;
   }

   res = yylex_destroy(scanner->scanner);

   aalclp_init_callbacks(&scanner->callbacks);
   scanner->scanner = NULL;

   return res;
}

AALCLP_API int
aalclp_scan_argv(aalclp *scanner, int argc, char *argv[]) {
   int             i;
   size_t          len;
   char           *scanbuf;
   char           *end;
   YY_BUFFER_STATE buf;

   len = 0;
   for ( i = 1 ; i < argc ; ++i ) {
      len += strlen(argv[i]);
      if ( i < (argc - 1) ) {
         ++len;
      }
   }

   if ( 0 == len ) {
      return 1;
   }

   scanbuf = (char *)malloc(len + 2);
   if ( NULL == scanbuf ) {
      return 2;
   }
   *scanbuf = 0;

   for ( i = 1 ; i < argc ; ++i ) {
      strcat(scanbuf, argv[i]);
      if ( i < (argc - 1) ) {
         strcat(scanbuf, " ");
      }
   }

   end = scanbuf + strlen(scanbuf);
   *end++ = YY_END_OF_BUFFER_CHAR;
   *end   = YY_END_OF_BUFFER_CHAR;

   buf = yy_scan_string(scanbuf,scanner->scanner);
   free(scanbuf);

   i = yylex(scanner->scanner);
   yy_delete_buffer(buf,scanner->scanner);

   return i;
}

AALCLP_API int
aalclp_scan_file(aalclp *scanner, FILE *in, FILE *out) {
   yyset_in(in,scanner->scanner);
   yyset_out(out,scanner->scanner);
   return yylex(scanner->scanner);
}


#define AALCLP_HANDLER0(__what, __type)                            \
static int                                                         \
aalclp_on_##__what(yyscan_t yyscanner) {                           \
   aalclp       *clp  = (aalclp *)yyget_extra(yyscanner);          \
   aalclp_links *head = &(clp->callbacks.listhead_##__what.links); \
   aalclp_links *iter;                                             \
   __type       *node;                                             \
   int           res;                                              \
   aalclp_list_for_each_entry(__type, node, head, iter) {          \
      res = node->cb(node->user);                                  \
      if ( 0 != res ) {                                            \
         return res;                                               \
      }                                                            \
   }                                                               \
   return res;                                                     \
}

#define AALCLP_HANDLER1(__what, __type, __param1type, __param1)    \
static int                                                         \
aalclp_on_##__what(yyscan_t yyscanner, __param1type __param1) {    \
   aalclp       *clp  = (aalclp *)yyget_extra(yyscanner);          \
   aalclp_links *head = &(clp->callbacks.listhead_##__what.links); \
   aalclp_links *iter;                                             \
   __type       *node;                                             \
   int           res;                                              \
   aalclp_list_for_each_entry(__type, node, head, iter) {          \
      res = node->cb(node->user, __param1);                        \
      if ( 0 != res ) {                                            \
         return res;                                               \
      }                                                            \
   }                                                               \
   return res;                                                     \
}

#define AALCLP_HANDLER2(__what, __type, __param1type, __param1, __param2type, __param2) \
static int                                                                              \
aalclp_on_##__what(yyscan_t yyscanner, __param1type __param1, __param2type __param2) {  \
   aalclp       *clp  = (aalclp *)yyget_extra(yyscanner);                               \
   aalclp_links *head = &(clp->callbacks.listhead_##__what.links);                      \
   aalclp_links *iter;                                                                  \
   __type       *node;                                                                  \
   int           res;                                                                   \
   aalclp_list_for_each_entry(__type, node, head, iter) {                               \
      res = node->cb(node->user, __param1, __param2);                                   \
      if ( 0 != res ) {                                                                 \
         return res;                                                                    \
      }                                                                                 \
   }                                                                                    \
   return res;                                                                          \
}

AALCLP_HANDLER1(nix_long_option_only,  aalclp_option_only, const char *, option)
AALCLP_HANDLER2(nix_long_option,       aalclp_option,      const char *, option, const char *, value)

AALCLP_HANDLER1(nix_short_option_only, aalclp_option_only, const char *, option)
AALCLP_HANDLER2(nix_short_option,      aalclp_option,      const char *, option, const char *, value)

AALCLP_HANDLER0(dash_only,             aalclp_dash_only)
AALCLP_HANDLER0(dash_dash_only,        aalclp_dash_only)

AALCLP_HANDLER1(win_long_option_only,  aalclp_option_only, const char *, option)
AALCLP_HANDLER2(win_long_option,       aalclp_option,      const char *, option, const char *, value)

AALCLP_HANDLER1(win_short_option_only, aalclp_option_only, const char *, option)
AALCLP_HANDLER2(win_short_option,      aalclp_option,      const char *, option, const char *, value)

AALCLP_HANDLER1(non_option,            aalclp_non_option,  const char *, nonoption)

AALCLP_HANDLER2(invalid,               aalclp_invalid,     const char *, invalid, size_t, len)


