#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='gdb-nightly'

. ./gdb-common

run_gdbtui "${VPATH}/tests/harnessed/gtest/.libs/nightly" ${1+"$@"}

exit $?
