#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='gdb-OSAL_TestSem'

. ./gdb-common

run_gdbtui "${VPATH}/tests/standalone/OSAL_TestSem/.libs/OSAL_TestSem" ${1+"$@"}

exit $?
