#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='lcov-swtest'

. ./lcov-common

declare -r D='swtest'

declare    ARGS='--gtest_print_time=0'
declare    WANTDISTCC=false

while [ $# -gt 0 ]; do
   case $1 in
      --distcc)
         WANTDISTCC=true
      ;;
      *)
         ARGS="${ARGS} $1"
      ;;
   esac
   shift
done

setup "$D" ${WANTDISTCC}

WHAT_TO_MEASURE="${VPATH}/tests/swtest --vpath=${VPATH} ${ARGS}"

GCDA_DIRS=(\
"--directory ${VPATH}/aas/OSAL/.libs" \
"--directory ${VPATH}/aas/AASLib/.libs" \
"--directory ${VPATH}/aas/AALRuntime/.libs" \
"--directory ${VPATH}/aas/AIAService/.libs" \
"--directory ${VPATH}/aas/RRMBrokerService/.libs" \
"--directory ${VPATH}/aas/AASResourceManager/.libs" \
"--directory ${VPATH}/utils/ALIAFU/ALI/.libs" \
"--directory ${VPATH}/tests/harnessed/gtest"\
)

run_lcov "$D"
exit $?
