#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='run-bat'

. ./run-common

declare ARGS="--gtest_print_time=0 --gtest_shuffle --gtest_random_seed=${RANDOM}"

declare WANTLOGFILE=false
declare WANTDISTCC=false
while [ $# -gt 0 ]; do
   case $1 in
      --log)
         WANTLOGFILE=true
      ;;
      --distcc)
         WANTDISTCC=true
      ;;
      *)
         ARGS="${ARGS} $1"
      ;;
   esac
   shift
done

setup ${WANTLOGFILE} ${WANTDISTCC}
run_bat ${ARGS}
show_test_result $?
exit $?
