#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='run-bat'

. ./run-common

declare -r ARGS="--gtest_print_time=0 --gtest_shuffle --gtest_random_seed=${RANDOM}"

setup
run_bat ${ARGS} ${1+"$@"}
exit $?
