#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='run-weekly'

. ./run-common

declare -ri REPEAT=400
declare -r  ARGS="--gtest_print_time=0 --gtest_shuffle --gtest_random_seed=${RANDOM} --gtest_repeat=${REPEAT}"

setup
run_weekly ${ARGS} ${1+"$@"}
exit $?
