#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

declare ARGS=''
while [ "x$1" != x ]; do

   case $1 in
      --gtest_*)
         ARGS="${ARGS} --gtest-opt=$1"
      ;;
      *)
         ARGS="${ARGS} $1"
      ;;
   esac

   shift
done

shopt -o -s nounset

declare -r SCRIPT_NAME='run-weekly'

. ./run-common

declare -r RANDOMIZE="--gtest-opt=--gtest_shuffle --gtest-opt=--gtest_random_seed=${RANDOM} --gtest-opt=--gtest_repeat=10000"

run_weekly ${ARGS} ${RANDOMIZE}
exit $?
