#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='run-standalone'

. ./run-common

declare ARGS=''

declare WANTLOGFILE=false
declare WANTDISTCC=false
while [ $# -gt 0 ]; do
   case $1 in
      --log)
         WANTLOGFILE=true
      ;;
      --distcc)
         WANTDISTCC=true
      ;;
      *)
         ARGS="${ARGS} $1"
      ;;
   esac
   shift
done

setup ${WANTLOGFILE} ${WANTDISTCC}
run_standalone ${ARGS}
show_test_result $?
exit $?
