#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='valgrind-everything'

. ./valgrind-common

declare ARGS=''
declare WANTDISTCC=false

while [ $# -gt 0 ]; do
   case $1 in
      --clean)
         clean_valgrind_all "tests/harnessed/gtest/.libs/bat"
         clean_valgrind_all "tests/harnessed/gtest/.libs/nightly"
         clean_valgrind_all "tests/harnessed/gtest/.libs/weekly"
         clean_valgrind_all "tests/standalone/OSAL_TestSem/.libs/OSAL_TestSem"
         clean_valgrind_all "tests/standalone/OSAL_TestThreadGroup/.libs/OSAL_TestThreadGroup"
         exit 0
      ;;
      --distcc)
         WANTDISTCC=true
      ;;
      *)
         ARGS="${ARGS} $1"
      ;;
   esac
   shift
done

run_valgrind_all ${WANTDISTCC} "tests/harnessed/gtest/.libs/bat" ${ARGS}
run_valgrind_all ${WANTDISTCC} "tests/harnessed/gtest/.libs/nightly" ${ARGS}
run_valgrind_all ${WANTDISTCC} "tests/harnessed/gtest/.libs/weekly" ${ARGS}
run_valgrind_all ${WANTDISTCC} "tests/standalone/OSAL_TestSem/.libs/OSAL_TestSem"
run_valgrind_all ${WANTDISTCC} "tests/standalone/OSAL_TestThreadGroup/.libs/OSAL_TestThreadGroup"
exit $?
