#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='valgrind-everything'

. ./valgrind-common

if [ $# -gt 0 ]; then
   if [ "$1" = 'clean' ]; then
      clean_valgrind_all "tests/harnessed/gtest/.libs/bat"
      clean_valgrind_all "tests/harnessed/gtest/.libs/nightly"
      clean_valgrind_all "tests/harnessed/gtest/.libs/weekly"
      clean_valgrind_all "tests/standalone/OSAL_TestSem/.libs/OSAL_TestSem"
      clean_valgrind_all "tests/standalone/OSAL_TestThreadGroup/.libs/OSAL_TestThreadGroup"
      exit 0
   fi
fi

run_valgrind_all "tests/harnessed/gtest/.libs/bat" ${1+"$@"}
run_valgrind_all "tests/harnessed/gtest/.libs/nightly" ${1+"$@"}
run_valgrind_all "tests/harnessed/gtest/.libs/weekly" ${1+"$@"}
run_valgrind_all "tests/standalone/OSAL_TestSem/.libs/OSAL_TestSem"
run_valgrind_all "tests/standalone/OSAL_TestThreadGroup/.libs/OSAL_TestThreadGroup"
exit $?
