#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='valgrind-standalone'

. ./valgrind-common

declare ARGS=''

declare WANTDISTCC=false
while [ $# -gt 0 ]; do
   case $1 in
      --clean)
         clean_valgrind_all "tests/standalone/OSAL_TestSem/.libs/OSAL_TestSem"
         clean_valgrind_all "tests/standalone/OSAL_TestThreadGroup/.libs/OSAL_TestThreadGroup"
         exit 0
      ;;
      --distcc)
         WANTDISTCC=true
      ;;
      *)
         ARGS="${ARGS} $1"
      ;;
   esac
   shift
done

run_valgrind_all ${WANTDISTCC} "tests/standalone/OSAL_TestSem/.libs/OSAL_TestSem" ${ARGS}
run_valgrind_all ${WANTDISTCC} "tests/standalone/OSAL_TestThreadGroup/.libs/OSAL_TestThreadGroup" ${ARGS}
exit $?
