#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='valgrind-nightly'

. ./valgrind-common

if [ $# -gt 0 ]; then
   if [ "$1" = 'clean' ]; then
      clean_valgrind_all "tests/harnessed/gtest/.libs/nightly"
      exit 0
   fi
fi

run_valgrind_all "tests/harnessed/gtest/.libs/nightly" ${1+"$@"}
exit $?
