#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='valgrind-swtest'

. ./valgrind-common

declare ARGS='--gtest_print_time=0'

declare WANTDISTCC=false
while [ $# -gt 0 ]; do
   case $1 in
      --clean)
         clean_valgrind_all "tests/harnessed/gtest/swtest/.libs/swtest"
         exit 0
      ;;
      --distcc)
         WANTDISTCC=true
      ;;
      *)
         ARGS="${ARGS} $1"
      ;;
   esac
   shift
done

run_valgrind_all ${WANTDISTCC} "tests/harnessed/gtest/swtest/.libs/swtest" ${ARGS}
exit $?
