#!/bin/bash
# INTEL CONFIDENTIAL - For Intel Internal Use Only

shopt -o -s nounset

declare -r SCRIPT_NAME='valgrind-nightly'

. ./valgrind-common

run_valgrind_all "tests/harnessed/gtest/.libs/nightly" ${1+"$@"}
exit $?
