#PRAGMA AUTORECOVER

[Dynamic, Provider("WMIProv"),
 WMI,
 Description("AAL Bus driver information"),
 guid("{0A78829F-0294-4723-822D-CA26B2BF7085}"),
 locale("MS\\0x409")]
class AALBusInformation
{
    [key, read]
     string InstanceName;
    [read] boolean Active;

    [WmiDataId(1),
     read,
     Description("Number of errors that occurred on this device")]
    uint32   ErrorCount;

    [WmiDataId(2),
     read,
     write,
     Description("The DebugPrintLevel property indicates the debug output level of toaster bus device.")]
    uint32 DebugPrintLevel;

};

